# Node.js Development Dockerfile
# Generated by BACO Docker Generator
# Optimized for hot reload and debugging

FROM node:18-alpine

# Install development tools
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    git \
    bash

# Install global development packages
RUN npm install -g \
    nodemon \
    ts-node \
    typescript \
    @types/node

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install all dependencies (including devDependencies)
RUN npm install

# Copy application code
# In development, we'll mount the source as a volume instead
# COPY . .

# Expose application port and debug port
EXPOSE 3000 5000 9229

# Enable Node.js debugging
ENV NODE_OPTIONS="--inspect=0.0.0.0:9229"

# Default command (override in docker-compose.yml)
CMD ["npm", "run", "dev"]